-- Roles
create type public.app_role as enum ('user', 'manager', 'admin');

-- Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Warehouses
create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  warehouse_id bigint not null references public.warehouses(id) on delete cascade,
  name text not null,
  category text,
  price numeric(12,2) not null default 0,
  cost_price numeric(12,2) not null default 0,
  status text not null default 'Available',
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Projects
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  client text,
  start_date date,
  end_date date,
  prepayment numeric(12,2) not null default 0,
  budget numeric(12,2) not null default 0,
  notes text,
  status text not null default 'Aktiv',
  progress integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Project items
create table if not exists public.project_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  warehouse_id bigint references public.warehouses(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  name text not null,
  days integer not null default 1,
  price_per_day numeric(12,2) not null default 0,
  cost_per_day numeric(12,2) not null default 0,
  start_date date,
  end_date date,
  provider text,
  total numeric(12,2) not null default 0,
  cost_total numeric(12,2) not null default 0,
  type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_warehouses_user_id on public.warehouses(user_id);
create index if not exists idx_products_user_id on public.products(user_id);
create index if not exists idx_products_warehouse_id on public.products(warehouse_id);
create index if not exists idx_projects_user_id on public.projects(user_id);
create index if not exists idx_project_items_user_id on public.project_items(user_id);
create index if not exists idx_project_items_project_id on public.project_items(project_id);

-- Keep updated_at current
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger trg_warehouses_updated_at
before update on public.warehouses
for each row execute function public.set_updated_at();

create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger trg_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

create trigger trg_project_items_updated_at
before update on public.project_items
for each row execute function public.set_updated_at();

-- Automatically create profile row after signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user')
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- RLS
alter table public.profiles enable row level security;
alter table public.warehouses enable row level security;
alter table public.products enable row level security;
alter table public.projects enable row level security;
alter table public.project_items enable row level security;

-- Profiles policies
create policy "profiles_select_own"
on public.profiles for select
using (id = auth.uid());

create policy "profiles_insert_own"
on public.profiles for insert
with check (id = auth.uid());

create policy "profiles_update_own"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

-- Warehouses policies
create policy "warehouses_select_own"
on public.warehouses for select
using (user_id = auth.uid());

create policy "warehouses_insert_own"
on public.warehouses for insert
with check (user_id = auth.uid());

create policy "warehouses_update_own"
on public.warehouses for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "warehouses_delete_own"
on public.warehouses for delete
using (user_id = auth.uid());

-- Products policies
create policy "products_select_own"
on public.products for select
using (user_id = auth.uid());

create policy "products_insert_own"
on public.products for insert
with check (user_id = auth.uid());

create policy "products_update_own"
on public.products for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "products_delete_own"
on public.products for delete
using (user_id = auth.uid());

-- Projects policies
create policy "projects_select_own"
on public.projects for select
using (user_id = auth.uid());

create policy "projects_insert_own"
on public.projects for insert
with check (user_id = auth.uid());

create policy "projects_update_own"
on public.projects for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "projects_delete_own"
on public.projects for delete
using (user_id = auth.uid());

-- Project items policies
create policy "project_items_select_own"
on public.project_items for select
using (user_id = auth.uid());

create policy "project_items_insert_own"
on public.project_items for insert
with check (user_id = auth.uid());

create policy "project_items_update_own"
on public.project_items for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "project_items_delete_own"
on public.project_items for delete
using (user_id = auth.uid());
